version: '3'
services:
  db:
    image: mysql:8.0.28
    platform: linux/x86_64
    container_name: daily_report
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: daily_report
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
