[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["kosuke-17 <tamutamu17@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
